### ISSUE TITLE
Pot throw items sprites are messed up

### ISSUE THREAD

**Issue by Brenin-Legend** [Bryan-Legend/Never-Split-The-Party#13]

**Comment by Bryan-Legend** [comment]
Explosive pots and pot stunning need icons set.

**Comment by Bryan-Legend** [comment]
![unknown](https://user-images.githubusercontent.com/920120/170900033-5f60788f-3a69-4751-8ae7-9218b37e58d1.png)

**Comment by Bryan-Legend** [comment]
Fixed
