### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by JohnFulpWillard** [Bryan-Legend/Never-Split-The-Party#23]
**Describe the bug**

I went to the 'Code' section of the Github and was unable to find the source code of the game.

**Choose a category**

**To Reproduce**
1. Go to Github
2. Click on Bryan-Legend/Never-Split-The-Party
3. Scroll down to 'Code'

**Expected behavior**

The source code to be displayed and available to download.

**Screenshots**

![image](https://github.com/Bryan-Legend/Never-Split-The-Party/assets/53777086/d1a8c9ef-233b-452a-9087-82b143edc384)

**Additional context**

I do not know where else the source code would be for me to download. I would assume it would be on Github as it is the largest Open Source sharing platform, except for perhaps Gitlab and Gitea.

**Comment by Bryan-Legend** [comment]
The game is not open source. This project is only here to be an issue tracker.
