### ISSUE TITLE
Water Witch Spawns not getting removed on game restart.

### ISSUE THREAD

**Issue by Brenin-Legend** [Bryan-Legend/Never-Split-The-Party#4]
After dying to one of these bosses: Water Witch, The Countess, or on occasion Pumpkin.

**Choose a category**
Please apply one of the Category labels using the options menu on the right.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, please grab and paste a screenshot here. Especially useful for visual issues or locations within the game.

**Additional context**

**Comment by Bryan-Legend** [comment]
Fixed. Please test.
