### ISSUE TITLE
Frenzy not being visible to players except for host. Also not being able to see the buff except for host.

### ISSUE THREAD

**Issue by Brenin-Legend** [Bryan-Legend/Never-Split-The-Party#7]

**Comment by Bryan-Legend** [comment]
-only the host of the server can see it most of the time even if not spawned by the server host. Only the server host can see the stat increase for any player but guest can't see their stats increasing when entering the AOE so not sure they are boosted by the sentinel
-the effect doesn't apply either on the host when a guest spawns a sentinel

**Comment by Bryan-Legend** [comment]
Fixed
