### ISSUE TITLE
Frenzy buff not removed when using stairs

### ISSUE THREAD

**Issue by Brenin-Legend** [Bryan-Legend/Never-Split-The-Party#8]
Test if the buff isn't removed when using doors or when using teleportation items like stonecutter or the potion of teleportation.

**Comment by Bryan-Legend** [comment]
Cool one that I will miss if you patch it but that is quite broken too, when you go through a stair by standing in the AOE, you will keep the stat boost for the rest of the game. I think it's because you are not recorded leaving the AOE at all so you don't get unboosted. Lot of fun with this one

**Comment by Bryan-Legend** [comment]
Fixed.
