### ISSUE TITLE
With two fear sentinels on top of each other you can perma fear everything in the room.

### ISSUE THREAD

**Issue by Brenin-Legend** [Bryan-Legend/Never-Split-The-Party#9]

**Comment by Brenin-Legend** [comment]
The suggested fix would be to add a boolean.
Bugfinders explanation:
-every 5 seconds, the sentinels applies Fear to all enemies in it's AOE for a duration of 5 seconds
-applying fear means they get a fear state timer and change their direction
-To keep record of the state of fear you set a timer of 5 seconds 
-To change the direction you multiply the direction vector by -1 
-So when 2 Sentinels apply fear at the same time, the timer for state of fear is set to 5 seconds twice but the direction is multiplied by -1 twice so it doesn't change at all.
-5 seconds later the fear state timer ends and the direction is multiplied by -1.
-However this effect is applied only once so the final result is direction still multiplied by -1
-By managing to lure the enemies in and out the fear AOE you can get them to stay in this state forever.

**Comment by Brenin-Legend** [comment]
Fear is extremely useful against the countess

**Comment by Bryan-Legend** [comment]
https://user-images.githubusercontent.com/920120/170884096-01c88eeb-5685-4f90-887b-00d1cbbf4668.mp4

**Comment by Bryan-Legend** [comment]
Fixed
